workspace 'OneShot'
xcodeproj 'OneShot.xcodeproj'

pod 'MBProgressHUD'
pod 'ZipArchive'
pod 'MMDrawerController', '~> 0.5.7'
pod 'MagicalRecord/Core+Logging', :git => 'https://github.com/magicalpanda/MagicalRecord.git', :branch => 'release/3.0'
pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git', :branch => 'release-2.0'
pod 'ConventionalC'
pod 'DeviceUtil', '~> 1.2'
pod 'Fabric'
pod 'Crashlytics'
pod 'ParseFacebookUtilsV4'
pod 'Parse'
pod 'ParseUI'
pod 'UIImage-Categories'
pod 'DECategories'
pod 'UIAlertView+Block'
